import { PostForm } from "@/components/forms/PostForm";
import { createPostAction } from "@/server/content/actions";
import { getPostEditorOptions } from "@/server/content/queries";
import { getMediaAssetOptions } from "@/server/media/service";

export default async function NewPostPage() {
  const [options, mediaAssets] = await Promise.all([
    getPostEditorOptions(),
    getMediaAssetOptions()
  ]);

  return (
    <div className="grid gap-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-slate-950">New post</h1>
        <p className="mt-1 text-sm text-slate-500">
          Create from a Chinese draft. The English version is generated by the configured AI.
        </p>
      </div>
      <PostForm
        action={createPostAction}
        categories={options.categories}
        tags={options.tags}
        mediaAssets={mediaAssets}
        submitLabel="Create post"
        generateEnglishFromChinese
      />
    </div>
  );
}
